### PR TITLE
add googleAuthR gadget

### PR DESCRIPTION
**Pull request by MarkEdmondson1234**

### CODE REVIEW

**Comment by daattali** [comment]
Sorry for the delay, I was about to add this but I tested it first

I just installed the package and ran the addin from the Addins menu. This is what I saw

image

I clicked on "Login" and got this error page

image

If this is expected because I didn't use the addin correctly, then I'll add it, but if it's an error maybe it should be fixed first?

**Comment by MarkEdmondson1234** [comment]
Ah yes, that's due to options needing to be set in the Google project first so it recognizes the port, I'll add some instructions. (Namely shiny.port=1221)

**Comment by daattali** [comment]
Alright, so the addin works, I can add it safely?

**Comment by MarkEdmondson1234** [comment]
Yes, I just added a note about the port, thanks!

**Comment by daattali** [comment]
Could you solve the merge conflict so I can merge the PR? I could add your line by myself, but I generally prefer to have the real author show up in the history and in the contributors :)  I'll do it if it's a needless hassle for you

**Comment by MarkEdmondson1234** [comment]
I tried to solve the conflict but couldn't work out how to do it, sorry about that :) I'll comment on it or something

**Comment by daattali** [comment]
How about you just submit a new PR, that should be easy

**Comment by daattali** [comment]
@MarkEdmondson1234  I'll add it myself if I don't get a PR soon

**Comment by MarkEdmondson1234** [comment]
Sorry I've not had the chance yet, the original PR was at 3am due to a baby :) 






On Tue, May 3, 2016 at 2:57 PM -0700, "Dean Attali" <notifications@github.com> wrote:












@MarkEdmondson1234  I'll add it myself if I don't get a PR soon

**Pull request closed without merging**
